name: Package Size Report

on:
  pull_request: {}

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  pkg-size-report:
    name: Package Size Report
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup
      - uses: wyvox/pkg-size@f1e6283bb99d2cf2afebab9cef02bc7d94d7b2c0
        with:
          build-command: "./bin/build-size-comparison-dists.sh"
          display-size: uncompressed, brotli
          unchanged-files: hide
          paths: |
            dist/dev
            dist/prod
            smoke-tests/v2-app-hello-world-template/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
